apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS genosentinel;
    ALTER USER 'root'@'%' IDENTIFIED BY 'Cris1233+@';
    FLUSH PRIVILEGES;
##Este archivo está ligado con la base de dato de mysql de Django, para crear una sola base de datos y
## evitar conflictos entre los dos volúmenes.